language: node_js
node_js:
  - 13

services:
  - docker

# Pre-testing installs
install:
  - echo "Step Install"

# Scripts to be run such as tests
before_script:
  - echo "Step Before Script"

script: 
  - docker --version # print the version for logging

  #udagram-api-feed
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker tag udagram-api-feed dongtiennguyen/udagram-api-feed:v3

  #udagram-api-user
  - docker build -t udagram-api-user ./udagram-api-user
  - docker tag udagram-api-user dongtiennguyen/udagram-api-user:v3

  #udagram-frontend
  - docker build -t udagram-frontend ./udagram-frontend
  - docker tag udagram-frontend dongtiennguyen/udagram-frontend:v3

  #udagram-reverseproxy
  - docker build -t udagram-reverseproxy ./udagram-reverseproxy
  - docker tag udagram-reverseproxy dongtiennguyen/udagram-reverseproxy:v3

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push dongtiennguyen/udagram-api-feed:v3
  - docker push dongtiennguyen/udagram-api-user:v3
  - docker push dongtiennguyen/udagram-frontend:v3
  - docker push dongtiennguyen/udagram-reverseproxy:v3